# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v3.4.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: requirements-txt-fixer
      - id: check-ast
      - id: debug-statements

  - repo: https://github.com/roy-ht/pre-commit-jupyter
    rev: "v1.2.1"
    hooks:
      - id: jupyter-notebook-cleanup
        args:
          # - --remove-kernel-metadata
          - --pin-patterns
          - "[pin];[donotremove]"

  - repo: https://github.com/psf/black
    rev: "20.8b1"
    hooks:
      - id: black
        name: black
        description: A formatter for Python files
        files: \.py$

  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort
        description: isort your imports, so you don't have to.
        files: \.py$

  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.9.0"
    hooks:
      - id: flake8
        name: flake8
        description: Your Tool For Style Guide Enforcement
        files: \.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.812"
    hooks:
      - id: mypy
        name: mypy
        description: Optional Static Typing for Python
        files: \.py$

  - repo: https://github.com/nbQA-dev/nbQA
    rev: "0.6.0"
    hooks:
      - id: nbqa-black
        additional_dependencies: [black==20.8b1]
        args: [--nbqa-mutate]
      - id: nbqa-pyupgrade
        additional_dependencies: [pyupgrade==2.10.0]
        args: [--nbqa-mutate, --py36-plus]
      - id: nbqa-isort
        additional_dependencies: [isort==5.7.0]
        args: [--nbqa-mutate]
      - id: nbqa-check-ast
        additional_dependencies: [pre-commit-hooks]
        args: [--nbqa-mutate]
      - id: nbqa-mypy
        additional_dependencies: [mypy]
        args: [--nbqa-mutate]

  - repo: https://github.com/awslabs/git-secrets
    rev: "master"
    hooks:
      - id: git-secrets
